<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caio dos Santos">
<meta name="dcterms.date" content="2026-04-03">

<title>Correlation and Simple Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c89800f59a5657e0c177b73a5ff15e5b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d250243be6510f45ae5a7bad6a98d8fc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-c89800f59a5657e0c177b73a5ff15e5b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-XRSH8JDS68"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-XRSH8JDS68', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Correlation and Simple Regression</h1>
            <p class="subtitle lead">Module 10</p>
                                <div class="quarto-categories">
                <div class="quarto-category">statistics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Caio dos Santos </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 3, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In the previous modules, we focused on comparing means across qualitative treatments.</p>
<ul>
<li>In modules 4 and 5, we compared two populations.</li>
<li>In modules 6 through 8, we compared multiple qualitative treatments.</li>
<li>In module 9, we discussed what to do when assumptions are not well behaved.</li>
</ul>
<p>The same assumptions apply in regression. The difference is not in the assumptions, but in how we model the mean: instead of a group mean, we use a continuous function of <span class="math inline">\(x\)</span>. Let’s keep that continuity in mind throughout this module.</p>
<p>In this module, we move to a different kind of question.</p>
<p>Instead of comparing only treatment groups identified by names (hybrid A, fungicide B, treatment C), we now study relationships between <strong>quantitative variables</strong>.</p>
<p>This is the big shift for units 10 and 11. In previous modules, treatments were categorical: hybrids, fungicides, or herbicides with names and labels. Those are different categories, but they are not naturally arranged on a numeric scale. Here, we move to variables like nitrogen rate, seed population, and canopy temperature. Because those are numerical and ordered, we can ask a different question: not just “are these groups different,” but “how much does <span class="math inline">\(y\)</span> change as <span class="math inline">\(x\)</span> changes,” and what do we predict between observed values?</p>
<p>Examples include:</p>
<ul>
<li>nitrogen rate and yield</li>
<li>plant biomass and fruit count</li>
<li>canopy temperature and grain moisture</li>
</ul>
<p>This module introduces two related but different tools:</p>
<ul>
<li><strong>correlation</strong>: measures association</li>
<li><strong>simple linear regression</strong>: models how one variable changes as another changes</li>
</ul>
</section>
<section id="correlation-versus-regression" class="level1">
<h1>Correlation versus Regression</h1>
<p>When we analyze two quantitative variables, the first practical question is:</p>
<blockquote class="blockquote">
<p>Are we only describing association, or are we modeling a directional relationship?</p>
</blockquote>
<p>The clearest way to see the difference is visually. Both plots below use the same example dataset. In one, we only summarize association. In the other, we fit a directional model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="correlation" class="level2">
<h2 class="anchored" data-anchor-id="correlation">Correlation</h2>
<p>Correlation measures the strength and direction of association between variables, usually represented as <span class="math inline">\(r\)</span>.</p>
<ul>
<li><span class="math inline">\(r\)</span> ranges from -1 to 1</li>
<li>values near 1 indicate a strong positive association</li>
<li>values near -1 indicate a strong negative association</li>
<li>values near 0 indicate weak or no linear association</li>
</ul>
<p>A key point:</p>
<blockquote class="blockquote">
<p>Correlation does not imply causation.</p>
</blockquote>
<p>One important limitation: <span class="math inline">\(r\)</span> only measures <strong>linear</strong> association. A strong curved relationship can still produce a low correlation coefficient because the two halves of the curve partially cancel each other out. Similarly, a single outlier can inflate <span class="math inline">\(r\)</span> substantially. This means a high <span class="math inline">\(r\)</span> alone is not enough. Always plot the data first.</p>
<p>The example below illustrates this. Despite a strong, clear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, the correlation coefficient is near zero because the curve is symmetric and the linear component cancels out.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<p>Simple linear regression is used when we want to model how a response variable <span class="math inline">\(y\)</span> changes with an explanatory variable <span class="math inline">\(x\)</span>.</p>
<p>In plain terms, regression lets us do three practical things:</p>
<ul>
<li>test whether <span class="math inline">\(x\)</span> is related to <span class="math inline">\(y\)</span></li>
<li>estimate the size of that relationship</li>
<li>predict <span class="math inline">\(y\)</span> for values of <span class="math inline">\(x\)</span> within the observed range</li>
</ul>
</section>
<section id="case-study-1-cucumber-traits" class="level2">
<h2 class="anchored" data-anchor-id="case-study-1-cucumber-traits">Case Study 1: Cucumber Traits</h2>
<p>An agronomist conducted a greenhouse experiment to understand the relationship between plant architecture and early productivity in cucumber. She grew 60 plants from the same seed lot under identical conditions and, at the flowering stage, harvested and dissected each plant to count:</p>
<ul>
<li>number of main stem branches</li>
<li>total number of leaves</li>
<li>number of fruits that had set by the flowering stage (“early fruits”)</li>
</ul>
<p>Her goal was to identify which traits correlate with early fruiting, which might help her breed for faster-producing varieties.</p>
<p>Here are the first few rows of the resulting dataset:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  branches leaves earlyfruit
1       76    572         15
2       78    482         21
3       50    382         19
4       53    500         14
5       83    641         20
6       80    825         18</code></pre>
</div>
</div>
<p>Let us first visualize branches versus leaves.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now branches versus early fruit.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In both plots, we see positive association. But this alone does not tell us whether one variable causes the other.</p>
<p>For example, do more branches enable more leaves to form, or does more active photosynthesis from abundant leaves fuel branch growth? Similarly, in indeterminate crops like tomatoes or soybeans, branches and fruits compete for the same carbohydrates, making the causal direction ambiguous. It’s also possible that a third variable, like total plant vigor, drives both branches and fruits upward independently. Correlation alone cannot resolve these questions.</p>
</section>
<section id="measuring-correlation-with-r" class="level2">
<h2 class="anchored" data-anchor-id="measuring-correlation-with-r">Measuring correlation with <span class="math inline">\(r\)</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(cucumber<span class="sc">$</span>branches, cucumber<span class="sc">$</span>leaves)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8221879</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(cucumber<span class="sc">$</span>branches, cucumber<span class="sc">$</span>earlyfruit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6157407</code></pre>
</div>
</div>
<p>That gives us a quick numerical summary of linear association strength.</p>
</section>
<section id="what-does-r-measure" class="level2">
<h2 class="anchored" data-anchor-id="what-does-r-measure">What does <span class="math inline">\(r\)</span> measure?</h2>
<p>One way to think about <span class="math inline">\(r\)</span> is that it takes covariance and puts it on a common scale.</p>
<p><span class="math display">\[
r = \frac{\mathrm{cov}(x, y)}{s_x s_y}
\]</span></p>
<ul>
<li><span class="math inline">\(\mathrm{cov}(x, y)\)</span> captures how <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> vary together</li>
<li><span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> scale by the variability of each variable</li>
</ul>
<p>That scaling step is why <span class="math inline">\(r\)</span> always stays between -1 and 1.</p>
<p>You do not need to memorize the formula. What matters most is:</p>
<ul>
<li>sign of <span class="math inline">\(r\)</span> gives direction of association</li>
<li>magnitude of <span class="math inline">\(r\)</span> gives strength of linear association</li>
</ul>
<p>A geometric way to picture this: imagine centering both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> around their means so the origin sits at <span class="math inline">\((\bar{x}, \bar{y})\)</span>. If points are aligned at approximately a 45-degree angle (northeast to southwest), their products accumulate with the same sign, driving <span class="math inline">\(r\)</span> toward <span class="math inline">\(\pm 1\)</span>. If points scatter randomly across all quadrants, positive and negative products cancel out, pushing <span class="math inline">\(r\)</span> toward 0. This is why the denominator (which measures the maximum possible alignment) keeps <span class="math inline">\(r\)</span> bounded between -1 and 1: it is scaling by the theoretical maximum covariance.</p>
<p>A natural bridge to regression is:</p>
<p><span class="math display">\[
\hat{\beta}_1 = r \cdot \frac{s_y}{s_x}
\]</span></p>
<p>This tells us that slope depends on both the correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> <strong>and</strong> the scales of the two variables. Two datasets with the same <span class="math inline">\(r\)</span> but different standard deviations will produce different slopes. Keeping this in mind helps avoid the common mistake of equating correlation magnitude with regression effect size.</p>
</section>
<section id="a-short-by-hand-correlation-example-in-r" class="level2">
<h2 class="anchored" data-anchor-id="a-short-by-hand-correlation-example-in-r">A short “by hand” correlation example in R</h2>
<p>Up to this point, we have mostly used <code>cor(x, y)</code> and taken the result at face value. That works perfectly fine, but it can feel a little like a black box.</p>
<p>So let’s slow down for a minute and actually see what is going on under the hood.</p>
<p>Suppose we have four paired observations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">10</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>xbar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ybar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.5</code></pre>
</div>
</div>
<p>First step: center both variables by subtracting their means. This just moves the data so that everything is measured relative to the average.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x_centered <span class="ot">&lt;-</span> x <span class="sc">-</span> xbar</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>y_centered <span class="ot">&lt;-</span> y <span class="sc">-</span> ybar</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(x, y, x_centered, y_centered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x  y x_centered y_centered
1 2  3       -2.5       -3.5
2 4  6       -0.5       -0.5
3 5  7        0.5        0.5
4 7 10        2.5        3.5</code></pre>
</div>
</div>
<p>Now here is the key idea.</p>
<ul>
<li>When <span class="math inline">\(x\)</span> is above average and <span class="math inline">\(y\)</span> is also above average → positive contribution</li>
<li>When <span class="math inline">\(x\)</span> is below average and <span class="math inline">\(y\)</span> is also below average → also positive</li>
<li>When one is above and the other is below → negative contribution</li>
</ul>
<p>So what we do is multiply these centered values together and add them up.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">&lt;-</span> <span class="fu">sum</span>(x_centered <span class="sc">*</span> y_centered)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>numerator</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
</div>
<p>That gives us a measure of how the variables move together. But we are not done yet, because this value depends on the scale of the data.</p>
<p>To fix that, we divide by the variability in each variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(x_centered <span class="sc">^</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sum</span>(y_centered <span class="sc">^</span> <span class="dv">2</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>denominator</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.02776</code></pre>
</div>
</div>
<p>Now we put it all together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>r_manual <span class="ot">&lt;-</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>r_manual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9984604</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(x, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9984604</code></pre>
</div>
</div>
<p>So this is all correlation is doing.</p>
<p>It is checking whether observations that are above average in <span class="math inline">\(x\)</span> tend to line up with observations that are above average in <span class="math inline">\(y\)</span>, and the same for below-average values.</p>
<p>Once you see it this way, <span class="math inline">\(r\)</span> stops being “just a number R gives you” and becomes a summary of how consistently the two variables move together.</p>
</section>
</section>
<section id="regression-1" class="level1">
<h1>Regression</h1>
<p>Now we move from association to modeling a directional relationship.</p>
<section id="case-study-2-nitrogen-rate-and-corn-yield" class="level2">
<h2 class="anchored" data-anchor-id="case-study-2-nitrogen-rate-and-corn-yield">Case Study 2: Nitrogen Rate and Corn Yield</h2>
<p>A crop consultant evaluated corn’s response to nitrogen fertilization on a farmer’s field. The farmer was considering three fertilizer programs: no applied nitrogen (baseline), a moderate rate (about 34 lbs/acre), and a high rate (about 67 lbs/acre), each applied to four randomly selected plots. At harvest, the consultant measured grain yield (standardized to 15% moisture) from each plot.</p>
<p>The goal was to estimate the relationship between nitrogen rate and yield so the farmer could make an economically informed decision about the optimal application rate.</p>
<p>Here are the first few rows of the harvest results:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   nitro     yield
1    0.0  9.202734
2    0.0  9.264649
3    0.0  7.611941
4    0.0  7.784601
5   33.6 11.286116
6   33.6 11.078984
7   33.6  9.807396
8   33.6 10.236354
9   67.2 14.366580
10  67.2 12.344108
11  67.2 11.259943
12  67.2 12.665017</code></pre>
</div>
</div>
<p>First, we always inspect the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nitrogen, <span class="fu">aes</span>(<span class="at">x =</span> nitro, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Nitrogen rate"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Yield"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_linedraw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The center of the points appears to increase approximately linearly with nitrogen, so a simple linear model is reasonable as a first approach.</p>
</section>
<section id="connecting-to-previous-linear-models" class="level2">
<h2 class="anchored" data-anchor-id="connecting-to-previous-linear-models">Connecting to previous linear models</h2>
<p>This part is important: you have seen this model structure before. Since module 6, we have been using the same linear additive framework:</p>
<p><span class="math display">\[{Y_{ij} = \mu + \tau_i + \varepsilon_{ij}}\]</span></p>
<p>where <span class="math inline">\(\tau_i\)</span> is a categorical treatment effect, a fixed shift in the mean for each group. When we called <code>lm(yield ~ trt)</code>, R was fitting exactly this model.</p>
<p>Simple linear regression uses that same framework, with one key change: the predictor is <strong>continuous</strong> instead of <strong>categorical</strong>.</p>
<p><span class="math display">\[{Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i}\]</span></p>
<p>Now <span class="math inline">\(\beta_1 x_i\)</span> replaces <span class="math inline">\(\tau_i\)</span>: instead of a separate mean shift for each group, the mean shifts continuously and proportionally as <span class="math inline">\(x\)</span> increases. The assumptions, the residual structure, and the hypothesis test are structurally identical.</p>
<p>The parallel with previous modules is:</p>
<ul>
<li>previous model: <span class="math inline">\(Y_{ij} = \mu + \tau_i + \varepsilon_{ij}\)</span></li>
<li>current model: <span class="math inline">\(Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\)</span></li>
<li>previous R call: <code>lm(yield ~ trt)</code> and <code>trt</code> is a <strong>categorical</strong> variable</li>
<li>current R call: <code>lm(yield ~ nitro)</code> and <code>nitro</code> is a <strong>continuous</strong> variable</li>
<li>previous null hypothesis: all <span class="math inline">\(\tau_i = 0\)</span></li>
<li>current null hypothesis: <span class="math inline">\(\beta_1 = 0\)</span></li>
</ul>
<p>So this is not a new statistical world. It is an extension of the one you already know.</p>
</section>
<section id="linear-equation" class="level2">
<h2 class="anchored" data-anchor-id="linear-equation">Linear equation</h2>
<p>The regression equation is:</p>
<p><span class="math display">\[{\hat{y} = \hat{\beta}_0 + \hat{\beta}_1x}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_0\)</span> is the intercept</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> is the slope</li>
</ul>
<p>Interpretation:</p>
<ul>
<li>intercept: expected <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span></li>
<li>slope: expected change in <span class="math inline">\(y\)</span> for each one-unit increase in <span class="math inline">\(x\)</span></li>
</ul>
<p>The diagram below annotates the fitted line directly to make both terms concrete on the plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="model-assumptions">Model assumptions</h2>
<p>For the usual inference from <code>summary()</code> to be reliable, we still need the same core assumptions:</p>
<ul>
<li><span class="math inline">\(x\)</span> is controlled by the researcher or measured with negligible error</li>
<li>the random errors are independent and have a common variance</li>
<li>the random errors are approximately normally distributed</li>
<li>the straight-line model is the correct functional form</li>
</ul>
<p>These are the same assumptions you already checked with residual plots in previous modules. The only difference is what we are modeling: instead of asking whether group means differ, we are asking whether a straight line captures how mean <span class="math inline">\(y\)</span> changes as <span class="math inline">\(x\)</span> changes.</p>
<p>One practical note on the intercept: interpreting <span class="math inline">\(\hat{\beta}_0\)</span> as the expected response when <span class="math inline">\(x = 0\)</span> only makes sense when <span class="math inline">\(x =
0\)</span> is within or close to the observed range. If no observations were taken near zero, the intercept is a mathematical anchor that positions the line, not a directly interpretable quantity. In the nitrogen example this is not a problem, because zero nitrogen is a real experimental condition and within the observed range.</p>
</section>
<section id="fitting-the-model-in-r" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-in-r">Fitting the model in R</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> nitro, <span class="at">data =</span> nitrogen)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ nitro, data = nitrogen)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.4122 -0.7130 -0.1676  0.7137  1.6944 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 8.479237   0.428456  19.790 2.38e-09 ***
nitro       0.062395   0.009877   6.317 8.72e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9387 on 10 degrees of freedom
Multiple R-squared:  0.7996,    Adjusted R-squared:  0.7796 
F-statistic:  39.9 on 1 and 10 DF,  p-value: 8.716e-05</code></pre>
</div>
</div>
<p>Worked interpretation example:</p>
<p>Suppose your model output shows an intercept near 8.5 and a slope near 0.05. A clear way to report that is: with zero nitrogen, expected yield is about 8.5 units, and each additional 1 unit of nitrogen is associated with an average increase of about 0.05 yield units. This does not mean every single observation increases by exactly 0.05. It means the <em>average trend</em> in the fitted line changes by that amount, while individual observations still vary around that trend due to residual variation.</p>
<p>Now we can overlay the fitted line.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-coefficients">Interpreting coefficients</h2>
<p>From the fitted model:</p>
<ul>
<li>the estimated intercept is the expected yield at zero nitrogen</li>
<li>the estimated slope is how much yield changes per unit nitrogen</li>
</ul>
<p>We can also make predictions for values inside the observed range (interpolation).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       nitro 
  8.4792367   0.0623948 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">nitro =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">50</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2 
 9.415159 11.598977 </code></pre>
</div>
</div>
</section>
<section id="least-squares-idea" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-idea">Least-squares idea</h2>
<p>The fitted line is chosen by least squares: it minimizes the sum of squared residuals.</p>
<p>Residual for each point:</p>
<p><span class="math display">\[{residual_i = y_i - \hat{y}_i}\]</span></p>
<p>Least squares chooses coefficients that minimize:</p>
<p><span class="math display">\[{\sum (y_i - \hat{y}_i)^2}\]</span></p>
<p>The red segments in the plot below show each individual residual. The fitted line is the one position that makes the sum of squared segment lengths as small as possible.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="a-quick-visualization-of-least-squares" class="level3">
<h3 class="anchored" data-anchor-id="a-quick-visualization-of-least-squares">A quick visualization of Least-squares</h3>
<p>This is a useful place to visualize how least squares chooses a slope.</p>
<p><strong>Important note:</strong> this is not the algorithm R uses internally for <code>lm()</code>. R solves the normal equations analytically for this model class. We are doing this only as a conceptual visualization. In the full least-squares problem, both the intercept and slope are estimated simultaneously. Here, we fix the intercept only to simplify visualization and isolate how the slope affects the error.</p>
<p>From our fitted model, the intercept is about 8.48 and the slope is about 0.05. We will keep the intercept fixed at 8.48 and try several candidate slope values. For each slope, we compute the sum of squared errors (SSE).</p>
<p>Now we plot the SSE for each candidate slope value. This gives the characteristic U-shape, with the minimum at the least-squares estimate.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="significance-of-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="significance-of-coefficients">Significance of coefficients</h2>
<p>In <code>anova(model1)</code>, the p-value for the slope tests:</p>
<ul>
<li><span class="math inline">\(H_0: \beta_1 = 0\)</span></li>
<li><span class="math inline">\(H_a: \beta_1 \ne 0\)</span></li>
</ul>
<p>If the p-value is small (for example, <span class="math inline">\(&lt; 0.05\)</span>), we have evidence that the slope is not zero, so there is a meaningful linear trend between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
</section>
<section id="analysis-of-variance-for-regression" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance-for-regression">Analysis of variance for regression</h2>
<p>You can also view the same model test through ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: yield
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
nitro      1 35.161  35.161  39.904 8.716e-05 ***
Residuals 10  8.812   0.881                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>For simple linear regression, this ANOVA test is equivalent to testing whether the slope differs from zero. So the logic is exactly the same as previous modules. The predictor changed from categorical to continuous, but the variation partition, F-statistic, and p-value interpretation follow the same workflow you already know.</p>
</section>
<section id="measuring-fit-with-r2" class="level2">
<h2 class="anchored" data-anchor-id="measuring-fit-with-r2">Measuring fit with <span class="math inline">\(R^2\)</span></h2>
<p>The model summary also reports <span class="math inline">\(R^2\)</span>.</p>
<ul>
<li><span class="math inline">\(R^2\)</span> is the proportion of variation in <span class="math inline">\(y\)</span> explained by the fitted line</li>
<li>values closer to 1 indicate better fit</li>
<li>values near 0 indicate little explanatory value</li>
</ul>
<p>A useful decomposition is:</p>
<p><span class="math display">\[{SST = SSR + SSE}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(SST\)</span> = total variation around the mean</li>
<li><span class="math inline">\(SSR\)</span> = variation explained by the model</li>
<li><span class="math inline">\(SSE\)</span> = residual (unexplained) variation</li>
</ul>
<p>So:</p>
<p><span class="math display">\[{R^2 = \frac{SSR}{SST}}\]</span></p>
<p>In simple linear regression, <span class="math inline">\(R^2\)</span> is also equal to the square of the Pearson correlation between observed and fitted values.</p>
<p>The short check below verifies this directly in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>y_obs <span class="ot">&lt;-</span> nitrogen<span class="sc">$</span>yield</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model1)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((y_obs <span class="sc">-</span> <span class="fu">mean</span>(y_obs))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> <span class="fu">sum</span>((y_hat <span class="sc">-</span> <span class="fu">mean</span>(y_obs))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>R2_manual <span class="ot">&lt;-</span> SSR <span class="sc">/</span> SST</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>R2_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(y_obs, y_hat)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">R2_manual =</span> R2_manual,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">R2_corr =</span> R2_corr,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">R2_summary =</span> <span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> R2_manual    R2_corr R2_summary 
 0.7996138  0.7996138  0.7996138 </code></pre>
</div>
</div>
<p>Two cautions are worth keeping in mind:</p>
<ul>
<li>a high <span class="math inline">\(R^2\)</span> does not prove the model is correct</li>
<li>a modest <span class="math inline">\(R^2\)</span> can still be scientifically useful in noisy biological systems if effect estimates are interpretable and diagnostics are acceptable</li>
</ul>
</section>
<section id="checking-model-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="checking-model-assumptions">Checking model assumptions</h2>
<p>Before trusting inferences and predictions, we inspect residuals.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What we want to see:</p>
<ul>
<li>no strong curvature in residuals vs fitted</li>
<li>no obvious funnel shape, which would indicate unequal variance across levels of <span class="math inline">\(x\)</span></li>
<li>residuals approximately following a straight line in normal Q-Q plot</li>
</ul>
<p>In this example, the data are clean and the diagnostics look reasonably well-behaved. In real experiments, however, the residual vs.&nbsp;fitted plot may reveal curvature (suggesting the relationship is not truly linear) or a funnel shape (suggesting unequal variance across <span class="math inline">\(x\)</span>). In those cases, the transformation and GLM tools from Module 9 apply here exactly as they did for ANOVA. The diagnostic workflow is the same.</p>
<section id="reality-check-fitting-a-line-to-curved-data" class="level3">
<h3 class="anchored" data-anchor-id="reality-check-fitting-a-line-to-curved-data">Reality check: fitting a line to curved data</h3>
<p>To emphasize why diagnostics are not optional, imagine the same consultant had tested nine nitrogen rates instead of three. Perhaps a research institute encouraged her to run a more detailed trial to better characterize the response curve. Here is what a more thorough trial might show:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> nitro, <span class="at">data =</span> nitrogen_full)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ nitro, data = nitrogen_full)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.91983 -0.25513 -0.01393  0.30859  0.72249 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 9.222308   0.135509   68.06  &lt; 2e-16 ***
nitro       0.017818   0.001423   12.52 2.75e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4409 on 34 degrees of freedom
Multiple R-squared:  0.8218,    Adjusted R-squared:  0.8165 
F-statistic: 156.8 on 1 and 34 DF,  p-value: 2.754e-14</code></pre>
</div>
</div>
<p>The summary looks impressive: a significant slope (p-value near 0) and <span class="math inline">\(R^2 \approx 0.82\)</span>.</p>
<p>Let’s take a look at the fitted line:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>But look at the residuals:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals show a strong curved pattern. The line systematically underpredicts at low and high nitrogen, but overpredicts in the middle. A significant p-value and high <span class="math inline">\(R^2\)</span> do not guarantee the model fits correctly. Only by inspecting residuals do we discover the true relationship is nonlinear (likely quadratic), and a straight line is inappropriate no matter how flat the summary statistics look.</p>
</section>
</section>
<section id="anscombes-quartet-why-plots-matter" class="level2">
<h2 class="anchored" data-anchor-id="anscombes-quartet-why-plots-matter">Anscombe’s quartet: why plots matter</h2>
<p>A classic reminder of why residual inspection matters comes from <a href="https://doi.org/10.1080/00031305.1973.10478966">Anscombe (1973)</a>. He constructed four datasets that are, for all practical purposes, numerically identical:</p>
<ul>
<li>same means and variances of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span></li>
<li>same fitted line: <span class="math inline">\(\hat{y} = 3 + 0.5x\)</span></li>
<li>same <span class="math inline">\(R^2 = 0.667\)</span></li>
<li>same F-statistic and p-value</li>
</ul>
<p>But when plotted, only one dataset shows a clean linear relationship. The others reveal curvature, a single influential outlier, and a perfectly collinear set interrupted by one extreme point.</p>
<p>This dataset is built into base R.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The takeaway is direct: identical numerical summaries can hide very different underlying structures. A high <span class="math inline">\(R^2\)</span> and a significant p-value do not substitute for looking at the data. This is exactly why we always plot before and after fitting, and why the diagnostics in the previous section are not optional.</p>
</section>
</section>
<section id="extrapolation" class="level1">
<h1>Extrapolation</h1>
<p>Interpolation is prediction <strong>within</strong> the observed range of <span class="math inline">\(x\)</span>.</p>
<p>Extrapolation is prediction <strong>outside</strong> that range.</p>
<p>Extrapolation can be risky because the true relationship may change outside the sampled region.</p>
<p>In this example, we observed nitrogen rates from 0 to 67.2. Predicting at 40 is interpolation. Predicting at 130 is extrapolation.</p>
<p>The shaded region below marks the observed range. The green point is within it; the red point is well outside.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="common-mistakes-to-avoid" class="level1">
<h1>Common mistakes to avoid</h1>
<ul>
<li>Treating correlation as proof of causation.</li>
<li>Reporting a significant p-value without interpreting effect size.</li>
<li>Interpreting a high <span class="math inline">\(R^2\)</span> as proof the model is correct.</li>
<li>Ignoring residual patterns because the slope is significant.</li>
<li>Concluding the relationship <strong>is</strong> linear just because the slope is significant: a curved trend can produce a non-zero linear component and a significant p-value even when the straight-line model is wrong.</li>
<li>Concluding there is <strong>no</strong> relationship just because the slope is non-significant: a curved relationship with zero linear slope will yield a non-significant p-value even though a real relationship exists. Always look at the scatter plot.</li>
<li>Extrapolating far outside sampled values as if uncertainty stayed the same.</li>
</ul>
<p>In practice, good interpretation combines all pieces of evidence: effect size, uncertainty, residual diagnostics, and biological plausibility.</p>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<p>In this module, we learned:</p>
<ul>
<li>Correlation quantifies association, not causation.</li>
<li>Regression models directional relationships and supports prediction.</li>
<li>The slope is the expected change in <span class="math inline">\(y\)</span> per unit change in <span class="math inline">\(x\)</span>.</li>
<li>Least squares fits the line by minimizing squared residuals.</li>
<li>Significance of the slope can be tested with coefficient tests or ANOVA.</li>
<li><span class="math inline">\(R^2\)</span> summarizes model fit.</li>
<li>Diagnostics are essential to check whether a linear model is appropriate.</li>
<li>Extrapolation should be approached cautiously.</li>
</ul>
<p>The key conceptual shift in this module is moving from comparing groups to modeling relationships. This allows us not only to detect differences, but to quantify how variables change together in biologically meaningful ways, and to make calibrated predictions for values we did not directly observe.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>