{
  "hash": "b165dc8206d9929b3a2d43636cfebc9f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Correlation and Simple Regression\"\nsubtitle: \"Module 10\"\nauthor: \"Caio dos Santos\"\ndate: \"2026-04-03\"\ncategories: [statistics]\n---\n\n\n\n# Introduction\n\nIn the previous modules, we focused on comparing means across\nqualitative treatments.\n\n-   In modules 4 and 5, we compared two populations.\n-   In modules 6 through 8, we compared multiple qualitative treatments.\n-   In module 9, we discussed what to do when assumptions are not well\n    behaved.\n\nThe same assumptions apply in regression. The difference is not in the\nassumptions, but in how we model the mean: instead of a group mean, we\nuse a continuous function of $x$. Let's keep that continuity in mind\nthroughout this module.\n\nIn this module, we move to a different kind of question.\n\nInstead of comparing only treatment groups identified by names (hybrid\nA, fungicide B, treatment C), we now study relationships between\n**quantitative variables**.\n\nThis is the big shift for units 10 and 11. In previous modules,\ntreatments were categorical: hybrids, fungicides, or herbicides with\nnames and labels. Those are different categories, but they are not\nnaturally arranged on a numeric scale. Here, we move to variables like\nnitrogen rate, seed population, and canopy temperature. Because those\nare numerical and ordered, we can ask a different question: not just\n\"are these groups different,\" but \"how much does $y$ change as $x$\nchanges,\" and what do we predict between observed values?\n\nExamples include:\n\n-   nitrogen rate and yield\n-   plant biomass and fruit count\n-   canopy temperature and grain moisture\n\nThis module introduces two related but different tools:\n\n-   **correlation**: measures association\n-   **simple linear regression**: models how one variable changes as\n    another changes\n\n# Correlation versus Regression\n\nWhen we analyze two quantitative variables, the first practical question\nis:\n\n> Are we only describing association, or are we modeling a directional\n> relationship?\n\nThe clearest way to see the difference is visually. Both plots below use\nthe same example dataset. In one, we only summarize association. In the\nother, we fit a directional model.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Correlation\n\nCorrelation measures the strength and direction of association between\nvariables, usually represented as $r$.\n\n-   $r$ ranges from -1 to 1\n-   values near 1 indicate a strong positive association\n-   values near -1 indicate a strong negative association\n-   values near 0 indicate weak or no linear association\n\nA key point:\n\n> Correlation does not imply causation.\n\nOne important limitation: $r$ only measures **linear** association. A\nstrong curved relationship can still produce a low correlation\ncoefficient because the two halves of the curve partially cancel each\nother out. Similarly, a single outlier can inflate $r$ substantially.\nThis means a high $r$ alone is not enough. Always plot the data first.\n\nThe example below illustrates this. Despite a strong, clear relationship\nbetween $x$ and $y$, the correlation coefficient is near zero because\nthe curve is symmetric and the linear component cancels out.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Regression\n\nSimple linear regression is used when we want to model how a response\nvariable $y$ changes with an explanatory variable $x$.\n\nIn plain terms, regression lets us do three practical things:\n\n-   test whether $x$ is related to $y$\n-   estimate the size of that relationship\n-   predict $y$ for values of $x$ within the observed range\n\n## Case Study 1: Cucumber Traits\n\nAn agronomist conducted a greenhouse experiment to understand the\nrelationship between plant architecture and early productivity in\ncucumber. She grew 60 plants from the same seed lot under identical\nconditions and, at the flowering stage, harvested and dissected each\nplant to count:\n\n-   number of main stem branches\n-   total number of leaves\n-   number of fruits that had set by the flowering stage (\"early\n    fruits\")\n\nHer goal was to identify which traits correlate with early fruiting,\nwhich might help her breed for faster-producing varieties.\n\nHere are the first few rows of the resulting dataset:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  branches leaves earlyfruit\n1       76    572         15\n2       78    482         21\n3       50    382         19\n4       53    500         14\n5       83    641         20\n6       80    825         18\n```\n\n\n:::\n:::\n\n\nLet us first visualize branches versus leaves.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nNow branches versus early fruit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIn both plots, we see positive association. But this alone does not tell\nus whether one variable causes the other.\n\nFor example, do more branches enable more leaves to form, or does more\nactive photosynthesis from abundant leaves fuel branch growth?\nSimilarly, in indeterminate crops like tomatoes or soybeans, branches\nand fruits compete for the same carbohydrates, making the causal\ndirection ambiguous. It's also possible that a third variable, like\ntotal plant vigor, drives both branches and fruits upward independently.\nCorrelation alone cannot resolve these questions.\n\n## Measuring correlation with $r$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cucumber$branches, cucumber$leaves)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8221879\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(cucumber$branches, cucumber$earlyfruit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6157407\n```\n\n\n:::\n:::\n\n\nThat gives us a quick numerical summary of linear association strength.\n\n## What does $r$ measure?\n\nOne way to think about $r$ is that it takes covariance and puts it on a\ncommon scale.\n\n$$\nr = \\frac{\\mathrm{cov}(x, y)}{s_x s_y}\n$$\n\n-   $\\mathrm{cov}(x, y)$ captures how $x$ and $y$ vary together\n-   $s_x$ and $s_y$ scale by the variability of each variable\n\nThat scaling step is why $r$ always stays between -1 and 1.\n\nYou do not need to memorize the formula. What matters most is:\n\n-   sign of $r$ gives direction of association\n-   magnitude of $r$ gives strength of linear association\n\nA geometric way to picture this: imagine centering both $x$ and $y$\naround their means so the origin sits at $(\\bar{x}, \\bar{y})$. If points\nare aligned at approximately a 45-degree angle (northeast to southwest),\ntheir products accumulate with the same sign, driving $r$ toward\n$\\pm 1$. If points scatter randomly across all quadrants, positive and\nnegative products cancel out, pushing $r$ toward 0. This is why the\ndenominator (which measures the maximum possible alignment) keeps $r$\nbounded between -1 and 1: it is scaling by the theoretical maximum\ncovariance.\n\nA natural bridge to regression is:\n\n$$\n\\hat{\\beta}_1 = r \\cdot \\frac{s_y}{s_x}\n$$\n\nThis tells us that slope depends on both the correlation between $x$ and\n$y$ **and** the scales of the two variables. Two datasets with the same\n$r$ but different standard deviations will produce different slopes.\nKeeping this in mind helps avoid the common mistake of equating\ncorrelation magnitude with regression effect size.\n\n## A short \"by hand\" correlation example in R\n\nUp to this point, we have mostly used `cor(x, y)` and taken the result\nat face value. That works perfectly fine, but it can feel a little like\na black box.\n\nSo let’s slow down for a minute and actually see what is going on under\nthe hood.\n\nSuppose we have four paired observations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(2, 4, 5, 7)\ny <- c(3, 6, 7, 10)\n\nxbar <- mean(x)\nybar <- mean(y)\n\nxbar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.5\n```\n\n\n:::\n\n```{.r .cell-code}\nybar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.5\n```\n\n\n:::\n:::\n\n\nFirst step: center both variables by subtracting their means. This just\nmoves the data so that everything is measured relative to the average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_centered <- x - xbar\ny_centered <- y - ybar\n\ndata.frame(x, y, x_centered, y_centered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x  y x_centered y_centered\n1 2  3       -2.5       -3.5\n2 4  6       -0.5       -0.5\n3 5  7        0.5        0.5\n4 7 10        2.5        3.5\n```\n\n\n:::\n:::\n\n\nNow here is the key idea.\n\n-   When $x$ is above average and $y$ is also above average → positive\n    contribution\n-   When $x$ is below average and $y$ is also below average → also\n    positive\n-   When one is above and the other is below → negative contribution\n\nSo what we do is multiply these centered values together and add them\nup.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumerator <- sum(x_centered * y_centered)\nnumerator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n:::\n\n\nThat gives us a measure of how the variables move together. But we are\nnot done yet, because this value depends on the scale of the data.\n\nTo fix that, we divide by the variability in each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndenominator <- sqrt(sum(x_centered ^ 2) * sum(y_centered ^ 2))\ndenominator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.02776\n```\n\n\n:::\n:::\n\n\nNow we put it all together:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_manual <- numerator / denominator\nr_manual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9984604\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9984604\n```\n\n\n:::\n:::\n\n\nSo this is all correlation is doing.\n\nIt is checking whether observations that are above average in $x$ tend\nto line up with observations that are above average in $y$, and the same\nfor below-average values.\n\nOnce you see it this way, $r$ stops being “just a number R gives you”\nand becomes a summary of how consistently the two variables move\ntogether.\n\n# Regression\n\nNow we move from association to modeling a directional relationship.\n\n## Case Study 2: Nitrogen Rate and Corn Yield\n\nA crop consultant evaluated corn's response to nitrogen fertilization on\na farmer's field. The farmer was considering three fertilizer programs:\nno applied nitrogen (baseline), a moderate rate (about 34 lbs/acre), and\na high rate (about 67 lbs/acre), each applied to four randomly selected\nplots. At harvest, the consultant measured grain yield (standardized to\n15% moisture) from each plot.\n\nThe goal was to estimate the relationship between nitrogen rate and\nyield so the farmer could make an economically informed decision about\nthe optimal application rate.\n\nHere are the first few rows of the harvest results:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   nitro     yield\n1    0.0  9.202734\n2    0.0  9.264649\n3    0.0  7.611941\n4    0.0  7.784601\n5   33.6 11.286116\n6   33.6 11.078984\n7   33.6  9.807396\n8   33.6 10.236354\n9   67.2 14.366580\n10  67.2 12.344108\n11  67.2 11.259943\n12  67.2 12.665017\n```\n\n\n:::\n:::\n\n\nFirst, we always inspect the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(nitrogen, aes(x = nitro, y = yield)) +\n  geom_point(pch = 21, size = 2.5) +\n  labs(x = \"Nitrogen rate\",\n       y = \"Yield\") +\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe center of the points appears to increase approximately linearly with\nnitrogen, so a simple linear model is reasonable as a first approach.\n\n## Connecting to previous linear models\n\nThis part is important: you have seen this model structure before. Since\nmodule 6, we have been using the same linear additive framework:\n\n$${Y_{ij} = \\mu + \\tau_i + \\varepsilon_{ij}}$$\n\nwhere $\\tau_i$ is a categorical treatment effect, a fixed shift in the\nmean for each group. When we called `lm(yield ~ trt)`, R was fitting\nexactly this model.\n\nSimple linear regression uses that same framework, with one key change:\nthe predictor is **continuous** instead of **categorical**.\n\n$${Y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i}$$\n\nNow $\\beta_1 x_i$ replaces $\\tau_i$: instead of a separate mean shift\nfor each group, the mean shifts continuously and proportionally as $x$\nincreases. The assumptions, the residual structure, and the hypothesis\ntest are structurally identical.\n\nThe parallel with previous modules is:\n\n-   previous model: $Y_{ij} = \\mu + \\tau_i + \\varepsilon_{ij}$\n-   current model: $Y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i$\n-   previous R call: `lm(yield ~ trt)` and `trt` is a **categorical**\n    variable\n-   current R call: `lm(yield ~ nitro)` and `nitro` is a **continuous**\n    variable\n-   previous null hypothesis: all $\\tau_i = 0$\n-   current null hypothesis: $\\beta_1 = 0$\n\nSo this is not a new statistical world. It is an extension of the one\nyou already know.\n\n## Linear equation\n\nThe regression equation is:\n\n$${\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1x}$$\n\nWhere:\n\n-   $\\hat{\\beta}_0$ is the intercept\n-   $\\hat{\\beta}_1$ is the slope\n\nInterpretation:\n\n-   intercept: expected $y$ when $x = 0$\n-   slope: expected change in $y$ for each one-unit increase in $x$\n\nThe diagram below annotates the fitted line directly to make both terms\nconcrete on the plot.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Model assumptions\n\nFor the usual inference from `summary()` to be reliable, we still need\nthe same core assumptions:\n\n-   $x$ is controlled by the researcher or measured with negligible\n    error\n-   the random errors are independent and have a common variance\n-   the random errors are approximately normally distributed\n-   the straight-line model is the correct functional form\n\nThese are the same assumptions you already checked with residual plots\nin previous modules. The only difference is what we are modeling:\ninstead of asking whether group means differ, we are asking whether a\nstraight line captures how mean $y$ changes as $x$ changes.\n\nOne practical note on the intercept: interpreting $\\hat{\\beta}_0$ as the\nexpected response when $x = 0$ only makes sense when $x =\n0$ is within or close to the observed range. If no observations were\ntaken near zero, the intercept is a mathematical anchor that positions\nthe line, not a directly interpretable quantity. In the nitrogen example\nthis is not a problem, because zero nitrogen is a real experimental\ncondition and within the observed range.\n\n## Fitting the model in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(yield ~ nitro, data = nitrogen)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield ~ nitro, data = nitrogen)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.4122 -0.7130 -0.1676  0.7137  1.6944 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 8.479237   0.428456  19.790 2.38e-09 ***\nnitro       0.062395   0.009877   6.317 8.72e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9387 on 10 degrees of freedom\nMultiple R-squared:  0.7996,\tAdjusted R-squared:  0.7796 \nF-statistic:  39.9 on 1 and 10 DF,  p-value: 8.716e-05\n```\n\n\n:::\n:::\n\n\nWorked interpretation example:\n\nSuppose your model output shows an intercept near 8.5 and a slope near\n0.05. A clear way to report that is: with zero nitrogen, expected yield\nis about 8.5 units, and each additional 1 unit of nitrogen is associated\nwith an average increase of about 0.05 yield units. This does not mean\nevery single observation increases by exactly 0.05. It means the\n*average trend* in the fitted line changes by that amount, while\nindividual observations still vary around that trend due to residual\nvariation.\n\nNow we can overlay the fitted line.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Interpreting coefficients\n\nFrom the fitted model:\n\n-   the estimated intercept is the expected yield at zero nitrogen\n-   the estimated slope is how much yield changes per unit nitrogen\n\nWe can also make predictions for values inside the observed range\n(interpolation).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       nitro \n  8.4792367   0.0623948 \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(model1, newdata = data.frame(nitro = c(15, 50)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2 \n 9.415159 11.598977 \n```\n\n\n:::\n:::\n\n\n## Least-squares idea\n\nThe fitted line is chosen by least squares: it minimizes the sum of\nsquared residuals.\n\nResidual for each point:\n\n$${residual_i = y_i - \\hat{y}_i}$$\n\nLeast squares chooses coefficients that minimize:\n\n$${\\sum (y_i - \\hat{y}_i)^2}$$\n\nThe red segments in the plot below show each individual residual. The\nfitted line is the one position that makes the sum of squared segment\nlengths as small as possible.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### A quick visualization of Least-squares\n\nThis is a useful place to visualize how least squares chooses a slope.\n\n**Important note:** this is not the algorithm R uses internally for\n`lm()`. R solves the normal equations analytically for this model class.\nWe are doing this only as a conceptual visualization. In the full\nleast-squares problem, both the intercept and slope are estimated\nsimultaneously. Here, we fix the intercept only to simplify\nvisualization and isolate how the slope affects the error.\n\nFrom our fitted model, the intercept is about 8.48 and the slope is\nabout 0.05. We will keep the intercept fixed at 8.48 and try several\ncandidate slope values. For each slope, we compute the sum of squared\nerrors (SSE).\n\nNow we plot the SSE for each candidate slope value. This gives the\ncharacteristic U-shape, with the minimum at the least-squares estimate.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## Significance of coefficients\n\nIn `anova(model1)`, the p-value for the slope tests:\n\n-   $H_0: \\beta_1 = 0$\n-   $H_a: \\beta_1 \\ne 0$\n\nIf the p-value is small (for example, $< 0.05$), we have evidence that\nthe slope is not zero, so there is a meaningful linear trend between $x$\nand $y$.\n\n## Analysis of variance for regression\n\nYou can also view the same model test through ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: yield\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nnitro      1 35.161  35.161  39.904 8.716e-05 ***\nResiduals 10  8.812   0.881                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nFor simple linear regression, this ANOVA test is equivalent to testing\nwhether the slope differs from zero. So the logic is exactly the same as\nprevious modules. The predictor changed from categorical to continuous,\nbut the variation partition, F-statistic, and p-value interpretation\nfollow the same workflow you already know.\n\n## Measuring fit with $R^2$\n\nThe model summary also reports $R^2$.\n\n-   $R^2$ is the proportion of variation in $y$ explained by the fitted\n    line\n-   values closer to 1 indicate better fit\n-   values near 0 indicate little explanatory value\n\nA useful decomposition is:\n\n$${SST = SSR + SSE}$$\n\nwhere:\n\n-   $SST$ = total variation around the mean\n-   $SSR$ = variation explained by the model\n-   $SSE$ = residual (unexplained) variation\n\nSo:\n\n$${R^2 = \\frac{SSR}{SST}}$$\n\nIn simple linear regression, $R^2$ is also equal to the square of the\nPearson correlation between observed and fitted values.\n\nThe short check below verifies this directly in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_obs <- nitrogen$yield\ny_hat <- fitted(model1)\n\nSST <- sum((y_obs - mean(y_obs))^2)\nSSR <- sum((y_hat - mean(y_obs))^2)\n\nR2_manual <- SSR / SST\nR2_corr <- cor(y_obs, y_hat)^2\n\nc(R2_manual = R2_manual,\n  R2_corr = R2_corr,\n  R2_summary = summary(model1)$r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n R2_manual    R2_corr R2_summary \n 0.7996138  0.7996138  0.7996138 \n```\n\n\n:::\n:::\n\n\nTwo cautions are worth keeping in mind:\n\n-   a high $R^2$ does not prove the model is correct\n-   a modest $R^2$ can still be scientifically useful in noisy\n    biological systems if effect estimates are interpretable and\n    diagnostics are acceptable\n\n## Checking model assumptions\n\nBefore trusting inferences and predictions, we inspect residuals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nWhat we want to see:\n\n-   no strong curvature in residuals vs fitted\n-   no obvious funnel shape, which would indicate unequal variance\n    across levels of $x$\n-   residuals approximately following a straight line in normal Q-Q plot\n\nIn this example, the data are clean and the diagnostics look reasonably\nwell-behaved. In real experiments, however, the residual vs. fitted plot\nmay reveal curvature (suggesting the relationship is not truly linear)\nor a funnel shape (suggesting unequal variance across $x$). In those\ncases, the transformation and GLM tools from Module 9 apply here exactly\nas they did for ANOVA. The diagnostic workflow is the same.\n\n### Reality check: fitting a line to curved data\n\nTo emphasize why diagnostics are not optional, imagine the same\nconsultant had tested nine nitrogen rates instead of three. Perhaps a\nresearch institute encouraged her to run a more detailed trial to better\ncharacterize the response curve. Here is what a more thorough trial\nmight show:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_full <- lm(yield ~ nitro, data = nitrogen_full)\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield ~ nitro, data = nitrogen_full)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.91983 -0.25513 -0.01393  0.30859  0.72249 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 9.222308   0.135509   68.06  < 2e-16 ***\nnitro       0.017818   0.001423   12.52 2.75e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4409 on 34 degrees of freedom\nMultiple R-squared:  0.8218,\tAdjusted R-squared:  0.8165 \nF-statistic: 156.8 on 1 and 34 DF,  p-value: 2.754e-14\n```\n\n\n:::\n:::\n\n\nThe summary looks impressive: a significant slope (p-value near 0) and\n$R^2 \\approx 0.82$.\n\nLet's take a look at the fitted line:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nBut look at the residuals:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe residuals show a strong curved pattern. The line systematically\nunderpredicts at low and high nitrogen, but overpredicts in the middle.\nA significant p-value and high $R^2$ do not guarantee the model fits\ncorrectly. Only by inspecting residuals do we discover the true\nrelationship is nonlinear (likely quadratic), and a straight line is\ninappropriate no matter how flat the summary statistics look.\n\n## Anscombe's quartet: why plots matter\n\nA classic reminder of why residual inspection matters comes from\n[Anscombe (1973)](https://doi.org/10.1080/00031305.1973.10478966). He\nconstructed four datasets that are, for all practical purposes,\nnumerically identical:\n\n-   same means and variances of $x$ and $y$\n-   same fitted line: $\\hat{y} = 3 + 0.5x$\n-   same $R^2 = 0.667$\n-   same F-statistic and p-value\n\nBut when plotted, only one dataset shows a clean linear relationship.\nThe others reveal curvature, a single influential outlier, and a\nperfectly collinear set interrupted by one extreme point.\n\nThis dataset is built into base R.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe takeaway is direct: identical numerical summaries can hide very\ndifferent underlying structures. A high $R^2$ and a significant p-value\ndo not substitute for looking at the data. This is exactly why we always\nplot before and after fitting, and why the diagnostics in the previous\nsection are not optional.\n\n# Extrapolation\n\nInterpolation is prediction **within** the observed range of $x$.\n\nExtrapolation is prediction **outside** that range.\n\nExtrapolation can be risky because the true relationship may change\noutside the sampled region.\n\nIn this example, we observed nitrogen rates from 0 to 67.2. Predicting\nat 40 is interpolation. Predicting at 130 is extrapolation.\n\nThe shaded region below marks the observed range. The green point is\nwithin it; the red point is well outside.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](correlation-and-simple-regression-lecture_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n# Common mistakes to avoid\n\n-   Treating correlation as proof of causation.\n-   Reporting a significant p-value without interpreting effect size.\n-   Interpreting a high $R^2$ as proof the model is correct.\n-   Ignoring residual patterns because the slope is significant.\n-   Concluding the relationship **is** linear just because the slope is\n    significant: a curved trend can produce a non-zero linear component\n    and a significant p-value even when the straight-line model is\n    wrong.\n-   Concluding there is **no** relationship just because the slope is\n    non-significant: a curved relationship with zero linear slope will\n    yield a non-significant p-value even though a real relationship\n    exists. Always look at the scatter plot.\n-   Extrapolating far outside sampled values as if uncertainty stayed\n    the same.\n\nIn practice, good interpretation combines all pieces of evidence: effect\nsize, uncertainty, residual diagnostics, and biological plausibility.\n\n# Summary\n\nIn this module, we learned:\n\n-   Correlation quantifies association, not causation.\n-   Regression models directional relationships and supports prediction.\n-   The slope is the expected change in $y$ per unit change in $x$.\n-   Least squares fits the line by minimizing squared residuals.\n-   Significance of the slope can be tested with coefficient tests or\n    ANOVA.\n-   $R^2$ summarizes model fit.\n-   Diagnostics are essential to check whether a linear model is\n    appropriate.\n-   Extrapolation should be approached cautiously.\n\nThe key conceptual shift in this module is moving from comparing groups\nto modeling relationships. This allows us not only to detect\ndifferences, but to quantify how variables change together in\nbiologically meaningful ways, and to make calibrated predictions for\nvalues we did not directly observe.\n",
    "supporting": [
      "correlation-and-simple-regression-lecture_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}